### ISSUE TITLE
code : 400 Reason : Invalid value 'NULL' for segment parameter.

### ISSUE THREAD

**Issue by donaldan** [gilliganondata/dartistics-googleanalytics#4]
Hi, I am trying to run the segments examples and keep getting these error messages 

code : 400 Reason : Invalid value 'NULL' for segment parameter.

I have used this query routine as I couldn't get the googleanalytics4() to work as for some reason it doenst like my viewed saying I don't have permissions? 
##############################################################
mobile_segment_v3 <- "sessions::condition::ga:deviceCategory==Mobile"

my_segment <- segment_ga4("Mobile Sessions Only",segment_id = mobile_segment_v3)
                          

query.list <- Init(start.date = "2017-11-01",
                   end.date = "2017-11-30",
                   dimensions = "ga:pagePath",
                   metrics = "ga:pageviews", 
                   segments = my_segment,
                   max.results=10000,
                   table.id = "ga:104288048")

ga.query <- QueryBuilder(query.list)

ga_data <- GetReportData(ga.query, token, split_daywise = T)

##############################################################
mobile_segment_v3 <- "sessions::condition::ga:deviceCategory==Mobile"

my_segment <- segment_ga4("Mobile Sessions Only",segment_id = mobile_segment_v3)
                          

query.list <- Init(start.date = "2017-11-01",
                   end.date = "2017-11-30",
                   dimensions = "ga:pagePath",
                   metrics = "ga:pageviews", 
                   segments = my_segment,
                   max.results=10000,
                   table.id = "ga:104288048")

ga.query <- QueryBuilder(query.list)

ga_data <- GetReportData(ga.query, token, split_daywise = T)

**Comment by gilliganondata** [comment]
Are you using the `googleAnalyticsR` package or the `RGoogleAnalytics` one? It looks like you've tried to combine the two, and I don't know that using the `segment_ga4()` function from `googleAnalyticsR` is necessarily going to build you a usable object within `GetReportData()` (which is from `RGoogleAnalytics`).

If the issue with using just `googleAnalyticsR` and the `google_analytics_4()` function had to do with inability to access a view, it's probably worth trying to figure out why that is, and then stick with a single Google Analytics access package for your code.

**Comment by donaldan** [comment]
Cheers Tim that worked a treat and yes was related to the library clash!

 

What I a trying to do is for a given GA A/C do some page value analysis and understand journeys 

 

I am  interested in the difference between users who's journey ends with them applying and the journeys of users who 

 

1. Get close but then exit

2. Users who apply but abandon

 

It would also be really useful to understand the journey by:

 

1. The number of times someone visits before the apply

2. The difference of journey between the times they visit to apply. I'm interest to understand if the journey between, 1st, 2nd etc visits differs, how it differs and what are the commonalities between the journeys and what factors cause them to apply?

 

Any advice here would be great on possible R approaches using the analytics tools?

 

Let me know

Kind regards

Andrew

**Comment by gilliganondata** [comment]
That's sort of one of the golden questions of web analytics. And, honestly, it's one that is really tricky to answer.

But, you're on the right track (and might actually have the background/skills to take it to a point that I'd love to get to in a "standard" way).

Definitely, starting with having segments that represent the different groups makes sense. I would think you would want maybe four of them:

1. Users who get close but then exit (presumably "viewed page X but not Y"
2. Users who apply but abandon ("viewed page Y but not...(something)?")
3. Users who applied and adopted (didn't abandon)
4. All other users

That would, essentially, give you a nominal variable with four levels, right?

The "typical" way to then look at that would be just diving into other characteristics of the traffic and see if you could find significant differences (channel, device category, landing page, etc.). That, generally, doesn't turn up much.

So, then there is the age-old "paths through the site" question. The challenge there is that there are very few "common paths" (or, the most common path... is land on the home page and exit, and that's only 5% of traffic, so it's not helpful on a couple of fronts). Sankey charts (http://www.dartistics.com/googleanalytics/adv-sankey.html) start to illustrate the messiness there. My sense is that there are a few different ways to tackle this in a more manageable way:

* Identify some key sequences of key pages and, with sequential segments, create variables that show how many of each group hit those various "pseudo-paths"
* Something with categorization / decision trees and the content... but I'm not entirely sure what, I'm afraid
* Simply identifying the top pages overall and then looking at the proportion of users in each group that viewed or did not view those pages (not necessarily worrying about the sequence)

As for the cross-session question, those are good ones, too. There is the ga:sessionCount dimension, which, honestly, I haven't played around with much, and I'm now kicking myself for that! Putting all the caveats about cookie deletion and the use of multiple devices, you might be able to use that and work backwards somewhat: 

1. How many times do users come to the site before they convert? 
2. Then, possibly with sequential, user-based segments, isolate "the session before the session where conversion happened" (and other groups). That may take some work -- it's a theory rather than something I've actually done.
